version: '3.0'

services:
  grafana:
    container_name: 'scenes-app-template'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.0-105543pre}
    ports:
      - 3001:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/scenes-app-template
      - ./provisioning:/etc/grafana/provisioning
      - ./provisioning/custom.ini:/etc/grafana/grafana.ini
